### ISSUE TITLE
Ask for the text size & color

### ISSUE THREAD

**Issue by heroiciota** [FarseaSH/hugo-theme-moments#23]
Dear developer: 
    Many thanks for this demo, I found the size and color or even front of website's name is often too shallow compared to the picture below, can you add this feature at your most convenience in future?
    Best wishes!
iota

**Comment by heroiciota** [comment]
also, I think it could be great if there have another function which can make our moments sorted automatically in months or years.
I need to say I am new here, I don't know whether it's a big work, but I would be happy if I could make some contribution besides  offering suggestion.

**Comment by FarseaSH** [comment]
Hi Iota,

Thank you for your nice advice. For your first issue, just go to the scss style file and change the heading style the way you want. You can find the setting in the file named `style-refractored.scss`. Then modify this part shown below. 

``` scss
.jumbotron{
    padding-top: 64px;
    background-position: center;
    background-size: cover; 
    min-height: 200px; 
    text-align: center;
    margin-bottom: 30px;

    .site-title{
        color: rgb(108, 117, 125);   // MODIFY THIS
        font-size: 56px; 
        font-weight: 300;    // MODIFY THIS
        margin-bottom: 20px;
    }
    
    .signature{
        color: rgba(0, 0, 0, 0.5);   // MODIFY THIS
        font-size: 20px;
        font-weight: 300;   // MODIFY THIS
    }
}
```

I would consider later put this setting in hugo config file so that it will be more straightforward to do so.

I am a litte confused about the second point you mentioned. What do you mean by "sorting the moments in months or years". Currently the moments are ordered from newest to oldest. Do you mean adding a feature that we can go to the moment we want by a timeline or something? Can you explain it in more detail?

Also, let me know if you have any other good thoughts on this project. Thanks!
